/*
UIL 2017
State - Arun
*/
/*

In a dream of going to State UIL one afternoon as he was napping, Arun came up with the following interesting pattern. Can you replicate it?

Input: None
Output: Write a program that displays the pattern you see below.

*/
import java.util.*;
import java.io.*;
import static java.lang.System.*;
class Arun
{
	public static void main(String [] args) throws IOException
	{
		String s = "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST";
		for (int r = 0;r < s.length(); r++){
		for (int c = 0;c < s.length(); c++){
			out.print(r%3==0?s.charAt(r):r%3==1?s.charAt(c):s.charAt(s.length()-1-c));
			}
			out.println();
		}
	}
}
/*
Output
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST
*/